version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'quarterly'
    commit-message:
      prefix: "chore"
      include: "none"
    groups:
      npm-packages:
        patterns: ['*']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'quarterly'
    commit-message:
      prefix: "chore"
      include: "none"
    groups:
      github-action-workflows:
        patterns: ['*']
