name: 'Pull request'
on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@fix/get-current-title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
